### PR TITLE
[WIP] Updating for Bacting 0.0.40

### PR DESCRIPTION
**Pull request by egonw**
This brings in [@bioregistry](https://twitter.com/bioregistry/) support:

```python
xref = bridgedb.compactIdentifier("ncbigene:1234");
```

### CODE REVIEW

**Comment by egonw** [comment]
@cthoyt, I have some problems with the internal logic. The dependencies do not seem to be downloaded properly. Do you have any clue what is going on?

```
==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_trivial.py ____________________
tests/test_trivial.py:9: in <module>
    import pybacting
.tox/py/lib/python3.10/site-packages/pybacting/__init__.py:5: in <module>
    from .api import (  # noqa:F401
.tox/py/lib/python3.10/site-packages/pybacting/api.py:49: in <module>
    start_jvm()
.tox/py/lib/python3.10/site-packages/scyjava/__init__.py:116: in start_jvm
    _, workspace = jgo.resolve_dependencies(
.tox/py/lib/python3.10/site-packages/jgo/jgo.py:665: in resolve_dependencies
    raise e
.tox/py/lib/python3.10/site-packages/jgo/jgo.py:[63](https://github.com/cthoyt/pybacting/runs/7163960021?check_suite_focus=true#step:5:64)6: in resolve_dependencies
    mvn_out = run_and_combine_outputs(mvn, *mvn_args)
.tox/py/lib/python3.10/site-packages/jgo/jgo.py:274: in run_and_combine_outputs
    return subprocess.check_output(command_string, stderr=subprocess.STDOUT)
/opt/hostedtoolcache/Python/3.10.5/x[64](https://github.com/cthoyt/pybacting/runs/7163960021?check_suite_focus=true#step:5:65)/lib/python3.10/subprocess.py:420: in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/subprocess.py:524: in run
    raise CalledProcessError(retcode, process.args,
E   subprocess.CalledProcessError: Command '('/usr/bin/mvn', '-B', '-f', '/home/runner/.jgo/io.github.egonw.bacting/managers-inchi/0.0.38/caba08eef1528fc425331118385026b51eda6dea99bcd0282efeb94aba4153fc/pom.xml', 'dependency:resolve')' returned non-zero exit status 1.
=========================== short test summary info ============================
ERROR tests/test_trivial.py - subprocess.CalledProcessError: Command '('/usr/...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 28.16s ===============================
ERROR: InvocationError for command /home/runner/work/pybacting/pybacting/.tox/py/bin/coverage run -p -m pytest --durations=20 tests (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   py: commands failed
Error: Process completed with exit code 1.
```

**Comment by egonw** [comment]
Seems Google Colab has the same problem with a previously released version:

image

**Comment by cthoyt** [comment]
So this is probably an upstream issue with scijava

**Comment by egonw** [comment]
Maybe I'm making progress on other fronts... now running into this issue: https://github.com/sphinx-doc/sphinx/issues/10491

**Comment by cthoyt** [comment]
> Maybe I'm making progress on other fronts... now running into this issue: [sphinx-doc/sphinx#10491](https://github.com/sphinx-doc/sphinx/issues/10491)

Yes, indeed, thanks for finding that fix. Unfortunately the implicit default for english was removed and every repository needs this update :/

**Comment by cthoyt** [comment]
As far as the maven resolution, it seems that something is relying on a version of `org.osgi.service.prefs` that no longer exists 

```
[ERROR] Failed to execute goal on project managers-inchi-BOOTSTRAPPER: Could not resolve dependencies for project io.github.egonw.bacting-BOOTSTRAPPER:managers-inchi-BOOTSTRAPPER:jar:0: Failed to collect dependencies at io.github.egonw.bacting:managers-inchi:jar:0.0.34 -> io.github.egonw.bacting:bacting-core:jar:0.0.34 -> io.github.egonw.bacting:bioclipse-core:jar:2.8.0.13 -> org.eclipse.platform:org.eclipse.core.runtime:jar:3.24.100 -> org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.0 -> org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0): No versions available for org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0) within specified range -> [Help 1]
```

This page says that only version 1.1.1 and 1.1.2 exist - https://search.maven.org/artifact/org.osgi/org.osgi.service.prefs

**Comment by egonw** [comment]
> This page says that only version 1.1.1 and 1.1.2 exist - https://search.maven.org/artifact/org.osgi/org.osgi.service.prefs

yes, but far as I know both fall in the range `[1.1.0,1.2.0)` ... :(

But I am considering this lead and in the progress of releasing Bacting 0.0.40 which depends on the new Eclipse core libraries that came up.

Another lead I have been trying is a comment somewhere that JGO has a hashing issue and mixing up versions in the local cache... that's why I tried deleting `/home/running/.jgo` at some point, but without success...

**Comment by egonw** [comment]
Okay, we're not the only ones having the issue :( 

https://code2care.org/maven/cannot-resolve-no-versions-available-for-org-osgi-service-prefs-jar-1-1-0-1-2-0-within-specified-range

**Comment by egonw** [comment]
So, Bacting 0.0.40 should fix it. It depends on the fixed libraries, but JGO/ScyJava is not picking up the libraries correctly. Here's the dependencies:

```
[INFO] ---------------< io.github.egonw.bacting:managers-inchi >---------------
[INFO] Building managers-inchi 0.0.40                                   [11/26]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ managers-inchi ---
[INFO] io.github.egonw.bacting:managers-inchi:jar:0.0.40
[INFO] +- xom:xom:jar:1.3.7:compile
[INFO] |  +- xerces:xercesImpl:jar:2.8.0:compile
[INFO] |  |  \- xml-apis:xml-apis:jar:1.3.03:compile
[INFO] |  \- xalan:xalan:jar:2.7.2:compile
[INFO] |     \- xalan:serializer:jar:2.7.2:compile
[INFO] +- io.github.egonw.bacting:bacting-core:jar:0.0.40:compile
[INFO] |  \- io.github.egonw.bacting:bioclipse-core:jar:2.8.0.16:compile
[INFO] |     +- org.eclipse.platform:org.eclipse.core.runtime:jar:3.25.0:compile
[INFO] |     |  +- org.eclipse.platform:org.eclipse.osgi:jar:3.18.0:compile (version selected from constraint [3.17.0,4.0.0))
[INFO] |     |  +- org.eclipse.platform:org.eclipse.equinox.common:jar:3.16.100:compile (version selected from constraint [3.16.0,))
[INFO] |     |  +- org.eclipse.platform:org.eclipse.core.jobs:jar:3.13.0:compile (version selected from constraint [3.13.0,4.0.0))
[INFO] |     |  +- org.eclipse.platform:org.eclipse.equinox.registry:jar:3.11.100:compile (version selected from constraint [3.11.0,4.0.0))
[INFO] |     |  +- org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.1:compile (version selected from constraint [3.10.0,4.0.0))
[INFO] |     |  |  \- org.osgi:org.osgi.service.prefs:jar:1.1.2:compile (version selected from constraint [1.1.0,1.2.0))
[INFO] |     |  |     \- org.osgi:osgi.annotation:jar:8.0.1:compile
[INFO] |     |  +- org.eclipse.platform:org.eclipse.core.contenttype:jar:3.8.100:compile (version selected from constraint [3.8.0,4.0.0))
[INFO] |     |  \- org.eclipse.platform:org.eclipse.equinox.app:jar:1.6.100:compile (version selected from constraint [1.6.0,))
[INFO] |     \- org.eclipse.platform:org.eclipse.core.resources:jar:3.17.0:compile
[INFO] |        +- org.eclipse.platform:org.eclipse.core.expressions:jar:3.8.100:compile (version selected from constraint [3.2.0,4.0.0))
[INFO] |        \- org.eclipse.platform:org.eclipse.core.filesystem:jar:1.9.400:compile (version selected from constraint [1.3.0,2.0.0))
```

But note that ScyJava is still looking for the old (wrong: `org.osgi.service:org.osgi.service.prefs` instead of the correct `org.osgi:org.osgi.service.prefs`) library... why???

```
Error: ] Failed to execute goal on project managers-inchi-BOOTSTRAPPER: Could not resolve dependencies for project io.github.egonw.bacting-BOOTSTRAPPER:managers-inchi-BOOTSTRAPPER:jar:0: Failed to collect dependencies at io.github.egonw.bacting:managers-inchi:jar:0.0.40 -> io.github.egonw.bacting:bacting-core:jar:0.0.40 -> io.github.egonw.bacting:bioclipse-core:jar:2.8.0.16 -> org.eclipse.platform:org.eclipse.core.runtime:jar:3.25.0 -> org.eclipse.platform:org.eclipse.equinox.preferences:jar:3.10.0 -> org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0): No versions available for org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0) within specified range -> [Help 1]
```

**Comment by egonw** [comment]
On the upside, at least I can reproduce it locally now. Maybe a confounding ScyJava bug after all?

**Comment by egonw** [comment]
I filed an issue to indicate pybacting is currently uninstallable: https://github.com/cthoyt/pybacting/issues/11

**Comment by egonw** [comment]
Okay, the workaround for the Eclipse problem worked. But now I got other problems (that should not even exist).

**Comment by egonw** [comment]
Well, at least Bacting is fixed:

image

Now I just need to figure out how to get pybacting working again too.

**Comment by egonw** [comment]
Replacing this with a clean new PR.

**Comment by egonw** [comment]
Yeah, I know. It was more for myself, so that I can see better what is happening.

**Pull request closed without merging**
